openapi: 3.0.3
info:
  title: LWB Backend API
  version: 0.1.0
servers:
  - url: https://api.example.com
paths:
  /v1/auth/validate:
    post:
      summary: Validate a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /v1/threads/{annotationId}:
    get:
      summary: Get thread messages
      parameters:
        - in: path
          name: annotationId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThreadMessage'
    post:
      summary: Add message to thread
      parameters:
        - in: path
          name: annotationId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessage'
      responses:
        '201':
          description: Created
components:
  schemas:
    ThreadMessage:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [text, image, audio, pdf]
        contentRef:
          type: string
        createdAt:
          type: string
          format: date-time
    NewMessage:
      type: object
      required: [type, contentRef]
      properties:
        type:
          type: string
          enum: [text, image, audio, pdf]
        contentRef:
          type: string
