name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Test Quality
    runs-on: ubuntu-latest
    env:
      ANDROID_COMPILE_SDK: 36
      ANDROID_BUILD_TOOLS: 34.0.0
      ANDROID_HOME: ${{ github.workspace }}/.android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Cache Android SDK
        id: cache-android
        uses: actions/cache@v4
        with:
          path: .android-sdk
          key: android-sdk-${{ env.ANDROID_COMPILE_SDK }}-bt-${{ env.ANDROID_BUILD_TOOLS }}

      - name: Download command line tools (if needed)
        if: steps.cache-android.outputs.cache-hit != 'true'
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d "$ANDROID_HOME/cmdline-tools"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"

      - name: Install / Update Android SDK packages
        run: |
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" \
            "platforms;android-${ANDROID_COMPILE_SDK}" \
            "build-tools;${ANDROID_BUILD_TOOLS}" \
            "platform-tools"
          mkdir -p "$ANDROID_HOME/licenses"
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --list | sed -n '1,120p' || true

      - name: Prepare Gradle
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew --stacktrace --parallel --build-cache assembleDebug

      - name: Unit Tests
        run: ./gradlew --stacktrace --parallel --build-cache testDebugUnitTest

      - name: Static Analysis (ktlint & detekt)
        run: ./gradlew --stacktrace --parallel --build-cache ktlintCheck detekt

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/testDebugUnitTest/

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: app/build/outputs/apk/**/debug/*.apk
          if-no-files-found: ignore

      - name: Upload Detekt Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt*'
          if-no-files-found: ignore

      - name: Upload Ktlint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-reports
          path: '**/build/reports/ktlint*'
          if-no-files-found: ignore
