name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: livewithoutbelief
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"perf","section":"Performance","hidden":false},
             {"type":"refactor","section":"Refactoring","hidden":false},
             {"type":"ci","section":"CI","hidden":false},
             {"type":"docs","section":"Documentation","hidden":false},
             {"type":"chore","section":"Chores","hidden":false}]
